# Generated by Django 3.1.7 on 2021-05-04 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название типа мероприятия')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
            ],
            options={
                'verbose_name': 'Тип научного мероприятия',
                'verbose_name_plural': 'Типы научных мероприятий',
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название мероприятия')),
                ('activity_date', models.DateField(verbose_name='Дата проведения')),
                ('participants', models.IntegerField(verbose_name='Число участников (всего)')),
                ('participants_university', models.IntegerField(verbose_name='Число участников (сотрудники, учащиеся ДВФУ)')),
                ('participants_foreign', models.IntegerField(verbose_name='Участие зарубежных специалистов (всего)')),
                ('participants_country', models.CharField(max_length=50, verbose_name='Участие зарубежных специалистов (страна)')),
                ('financing_source', models.CharField(max_length=300, verbose_name='Финансирование (фонд, организация)')),
                ('financing_amount', models.FloatField(verbose_name='Финансирование (руб.)')),
                ('bibliographic_description', models.TextField(verbose_name='Материалы конференции (полное библиографическое описание)')),
                ('publications_url', models.URLField(verbose_name='Ссылки на публикации о мероприятии')),
                ('journal_name', models.CharField(blank=True, max_length=100, verbose_name='Указать название журнала, сборника, если планируется индексация материалов в БД Scopus')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.activitytype', verbose_name='Тип научного мероприятия')),
            ],
            options={
                'verbose_name': 'Научное мероприятие',
                'verbose_name_plural': 'Научные мероприятия',
            },
        ),
    ]
