# Generated by Django 3.0.6 on 2020-06-22 11:17

import apps.common.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scholarships', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scholarship',
            options={'ordering': ['category'], 'verbose_name': 'Поддержка', 'verbose_name_plural': 'Поддержка'},
        ),
        migrations.AlterModelOptions(
            name='scholarshipcategory',
            options={'verbose_name': 'Категория поддержки', 'verbose_name_plural': 'Категории поддержки'},
        ),
        migrations.RemoveField(
            model_name='scholarship',
            name='name',
        ),
        migrations.AddField(
            model_name='scholarship',
            name='fond',
            field=models.CharField(default='Test', max_length=150, verbose_name='Название фонда'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='activity',
            field=models.CharField(blank=True, max_length=250, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholarships.ScholarshipCategory', verbose_name={'plural': 'Категории поддержки', 'singular': 'Категория поддержки'}),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='financing',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем финансирования'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), size=None, verbose_name='Участники'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='support_type',
            field=models.CharField(max_length=100, verbose_name='Форма поддержки'),
        ),
        migrations.AlterField(
            model_name='scholarship',
            name='time_period',
            field=models.CharField(blank=True, max_length=50, verbose_name='Сроки выполнения'),
        ),
    ]
