# Generated by Django 3.0.5 on 2020-05-07 02:08

import apps.articles.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BibliographicDatabase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Библиографическая база данных',
                'verbose_name_plural': 'Библиографические базы данных',
            },
        ),
        migrations.CreateModel(
            name='PublicationType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Тип публикации',
                'verbose_name_plural': 'Типы публикации',
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('impact', models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Импакт-фактор')),
                ('employee_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, default=list, size=None, verbose_name='Авторы (сотрудники)')),
                ('foreign_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, default=list, size=None, verbose_name='Авторы (иностранцы)')),
                ('postgraduate_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, default=list, size=None, verbose_name='Авторы (аспиранты, докторанты)')),
                ('student_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, default=list, size=None, verbose_name='Авторы (студенты)')),
                ('url', models.URLField(verbose_name='Ссылка на публикацию')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('bibliographic_databases', models.ManyToManyField(related_name='articles', to='articles.BibliographicDatabase', verbose_name='Библиографическая база данных')),
                ('publication_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='articles.PublicationType', verbose_name='Тип публикации')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
