# Generated by Django 3.0.5 on 2020-05-08 03:31

import apps.articles.models
import django.contrib.postgres.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='employee_authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (сотрудники)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='foreign_authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (иностранцы)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='postgraduate_authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (аспиранты, докторанты)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='student_authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=apps.articles.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (студенты)'),
        ),
    ]
