# Generated by Django 3.0.6 on 2020-06-15 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200508_0331'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['description'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
