# Generated by Django 3.0.6 on 2020-06-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200615_0923'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Категории статьи',
            },
        ),
    ]
