# Generated by Django 3.0.6 on 2020-06-22 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articlecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'verbose_name': 'Категория статьи', 'verbose_name_plural': 'Категории статьи'},
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='articles.ArticleCategory', verbose_name='Категория'),
            preserve_default=False,
        ),
    ]
