# Generated by Django 3.0.6 on 2020-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_auto_20200622_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecategory',
            name='name',
            field=models.CharField(max_length=350, verbose_name='Наименование'),
        ),
    ]
