# Generated by Django 3.0.6 on 2020-06-15 09:57

import apps.common.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=150, verbose_name='Grant Name')),
                ('contest_name', models.CharField(max_length=250, verbose_name='Название конкурса')),
                ('project_name', models.CharField(max_length=200, verbose_name='Prject Name')),
                ('time_period', models.CharField(max_length=50, verbose_name='Time Period')),
                ('financing', models.CharField(max_length=50, verbose_name='Financing')),
                ('grant_manager', models.CharField(max_length=100, verbose_name='Grant Manager')),
                ('participants', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), size=None, verbose_name='Participants')),
                ('postgraduates_number_payed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Postgraduates (payed)')),
                ('postgraduates_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Postgraduates')),
                ('students_number_payed', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Students (payed)')),
                ('students_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Number of Students')),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Grant',
                'verbose_name_plural': 'Grants',
                'ordering': ['grant_name'],
            },
        ),
    ]
