# Generated by Django 3.0.6 on 2020-06-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['grant'], 'verbose_name': 'Grant', 'verbose_name_plural': 'Grants'},
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='contest_name',
            new_name='contest',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='grant_name',
            new_name='grant',
        ),
        migrations.RenameField(
            model_name='grant',
            old_name='project_name',
            new_name='project',
        ),
    ]
