# Generated by Django 3.0.6 on 2020-06-22 06:32

import apps.common.models
import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0003_auto_20200615_1011'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grant',
            options={'ordering': ['fond'], 'verbose_name': 'Грант зарубежного фонда', 'verbose_name_plural': 'Гранты зарубежных фондов'},
        ),
        migrations.RemoveField(
            model_name='grant',
            name='grant',
        ),
        migrations.AddField(
            model_name='grant',
            name='fond',
            field=models.CharField(default='Test', max_length=150, verbose_name='Название фонда/организации'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='grant',
            name='financing',
            field=models.CharField(max_length=50, verbose_name='Объем финансирования'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='grant_manager',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='grant',
            name='participants',
            field=django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), size=None, verbose_name='Участники гранта'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='postgraduates_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество аспирантов и докторантов в научной коллективе на безвозмездной основе'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='postgraduates_number_payed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество аспирантов и докторантов в научной коллективе на возмездной основе'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='project',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='students_number',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grant',
            name='students_number_payed',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='grant',
            name='time_period',
            field=models.CharField(max_length=50, verbose_name='Сроки выполнения'),
        ),
    ]
