# Generated by Django 3.0.6 on 2020-06-22 11:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0005_auto_20200622_0632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grant',
            name='postgraduates_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество аспирантов и докторантов в научной коллективе на безвозмездной основе'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='postgraduates_number_payed',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество аспирантов и докторантов в научной коллективе на возмездной основе'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='students_number',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество студентов в научном коллективе на безвозмездной основе'),
        ),
        migrations.AlterField(
            model_name='grant',
            name='students_number_payed',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Количество студентов в научном коллективе на безвозмездной основе'),
        ),
    ]
