# Generated by Django 3.0.5 on 2020-05-07 09:47

import apps.common.models
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('employee_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (сотрудники)')),
                ('foreign_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (иностранцы)')),
                ('postgraduate_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (аспиранты, докторанты)')),
                ('student_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (студенты)')),
            ],
            options={
                'verbose_name': 'Conference',
                'verbose_name_plural': 'Conferences',
            },
        ),
    ]
