# Generated by Django 3.0.5 on 2020-05-08 01:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0002_auto_20200508_0151'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='conference_type',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.PROTECT, to='conferences.ConferenceType', verbose_name='Conference Type'),
            preserve_default=False,
        ),
    ]
