# Generated by Django 3.0.6 on 2020-06-15 09:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0004_auto_20200508_0156'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['description'], 'verbose_name': 'Конференция', 'verbose_name_plural': 'Конференции'},
        ),
        migrations.AlterModelOptions(
            name='conferencetype',
            options={'verbose_name': 'Тип конференции', 'verbose_name_plural': 'Типы конференций'},
        ),
        migrations.AddField(
            model_name='conference',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='conference_type',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='conferences.ConferenceType', verbose_name='Тип конференции'),
        ),
    ]
