# Generated by Django 3.0.6 on 2020-06-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0006_auto_20200620_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='conference',
            old_name='employee_participants',
            new_name='employee_authors',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='foreign_participants',
            new_name='foreign_authors',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='postgraduate_participants',
            new_name='postgraduate_authors',
        ),
        migrations.RenameField(
            model_name='conference',
            old_name='student_participants',
            new_name='student_authors',
        ),
    ]
