# Generated by Django 3.0.6 on 2020-06-20 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0007_auto_20200620_0840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conference',
            options={'ordering': ['description'], 'verbose_name': 'Конференция', 'verbose_name_plural': None},
        ),
    ]
