# Generated by Django 3.0.6 on 2020-06-21 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0008_auto_20200620_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='conference',
            name='description',
            field=models.TextField(unique=True, verbose_name='Описание'),
        ),
    ]
