# Generated by Django 3.0.6 on 2020-06-21 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conferences', '0009_auto_20200621_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conference',
            name='conference_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='conferences.ConferenceType', verbose_name='Тип конференции'),
        ),
    ]
