# Generated by Django 3.0.6 on 2020-06-22 13:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0002_auto_20200616_0416'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fieldofstudy',
            options={'verbose_name': 'Область исследования', 'verbose_name_plural': 'Области исследования'},
        ),
        migrations.AlterModelOptions(
            name='guide',
            options={'ordering': ['description'], 'verbose_name': 'Учебно-методическое пособие', 'verbose_name_plural': 'Учебно-методические пособия'},
        ),
        migrations.AlterModelOptions(
            name='guidecategory',
            options={'verbose_name': 'Категория учебно-методического пособия', 'verbose_name_plural': 'Категории учебно-методических пособий'},
        ),
        migrations.AlterModelOptions(
            name='manual',
            options={'verbose_name': 'Учебное пособие', 'verbose_name_plural': 'Учебные пособия'},
        ),
        migrations.AlterModelOptions(
            name='manualcategory',
            options={'verbose_name': 'Категория учебного пособия', 'verbose_name_plural': 'Категории учебных пособий'},
        ),
        migrations.AlterModelOptions(
            name='textbook',
            options={'verbose_name': 'Учебник', 'verbose_name_plural': 'Учебники'},
        ),
        migrations.AlterModelOptions(
            name='textbookcategory',
            options={'verbose_name': 'Категория учебника', 'verbose_name_plural': 'Категории учебников'},
        ),
        migrations.AlterField(
            model_name='fieldofstudy',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='circulation',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='description',
            field=models.TextField(verbose_name='Библиографическое описание'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='field_of_study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='textbooks.FieldOfStudy', verbose_name='Область исследования'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='volume_employees',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем, выполненный штантыми преподавателями'),
        ),
        migrations.AlterField(
            model_name='guidecategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='circulation',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='description',
            field=models.TextField(verbose_name='Библиографическое описание'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='field_of_study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='textbooks.FieldOfStudy', verbose_name='Область исследования'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='volume_employees',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем, выполненный штантыми преподавателями'),
        ),
        migrations.AlterField(
            model_name='manualcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='circulation',
            field=models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='description',
            field=models.TextField(verbose_name='Библиографическое описание'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='field_of_study',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='textbooks.FieldOfStudy', verbose_name='Область исследования'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='volume_employees',
            field=models.DecimalField(decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем, выполненный штантыми преподавателями'),
        ),
        migrations.AlterField(
            model_name='textbookcategory',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название'),
        ),
    ]
