# Generated by Django 3.0.6 on 2020-06-22 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0003_auto_20200622_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='guide',
            name='volume_employees',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем, выполненный штантыми преподавателями'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='volume_employees',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем, выполненный штантыми преподавателями'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем'),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='volume_employees',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Объем, выполненный штантыми преподавателями'),
        ),
    ]
