# Generated by Django 3.0.6 on 2020-06-22 13:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('textbooks', '0005_auto_20200622_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='circulation',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manual',
            name='circulation',
            field=models.IntegerField(blank=True, default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='textbook',
            name='circulation',
            field=models.IntegerField(blank=True, default='1', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Тираж'),
            preserve_default=False,
        ),
    ]
