# Generated by Django 3.0.5 on 2020-05-08 01:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universityuser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Указывает, следует ли считать этого пользователя активным.', verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Указывает, может ли пользователь войти на этот сайт администратора.', verbose_name='Персонал'),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='universityuser',
            name='patronimic_name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Отчество'),
        ),
    ]
