# Generated by Django 3.0.6 on 2020-06-08 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200508_0151'),
        ('accounts', '0002_auto_20200508_0331'),
    ]

    operations = [
    ]
