# Generated by Django 3.0.6 on 2020-06-15 12:35

import apps.common.models
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Field of Study',
                'verbose_name_plural': 'Fields of Study',
            },
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('employee_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (сотрудники)')),
                ('foreign_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (иностранцы)')),
                ('postgraduate_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (аспиранты, докторанты)')),
                ('student_authors', django.contrib.postgres.fields.ArrayField(base_field=apps.common.models.AuthorField(max_length=25), blank=True, size=None, verbose_name='Авторы (студенты)')),
                ('date_added', models.DateField(auto_now_add=True)),
                ('field_of_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='popular_science.FieldOfStudy', verbose_name='Field of Study')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['description'],
            },
        ),
    ]
