# Generated by Django 3.0.6 on 2020-06-07 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='CriticalTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='EconomicPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='ScientificPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='StrategicDirection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityPriority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
            ],
        ),
        migrations.CreateModel(
            name='Research',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя')),
                ('academic_advisor', models.CharField(max_length=50, verbose_name='Academic Advisor')),
                ('reasons', models.TextField(verbose_name='Reason')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Category', verbose_name='CSCSTI')),
                ('critical_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.CriticalTechnology', verbose_name='Critical Technology')),
                ('economic_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.EconomicPriority', verbose_name='Economical Priority')),
                ('scientific_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ScientificPriority', verbose_name='Scientific Priority')),
                ('strategic_direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.StrategicDirection', verbose_name='Strategic Direction')),
                ('university_priority', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.UniversityPriority', verbose_name='University Priority')),
            ],
        ),
    ]
