# Generated by Django 3.0.6 on 2020-06-07 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0002_auto_20200607_0820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='research',
            options={'ordering': ['name'], 'verbose_name': 'Research', 'verbose_name_plural': 'Research'},
        ),
        migrations.AddField(
            model_name='category',
            name='code',
            field=models.IntegerField(default=0, unique=True, verbose_name='Code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=150, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='criticaltechnology',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='economicpriority',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='research',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='scientificpriority',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='strategicdirection',
            name='name',
            field=models.CharField(max_length=250, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='universitypriority',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='Имя'),
        ),
    ]
