# Generated by Django 3.0.6 on 2020-06-07 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0004_auto_20200607_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^(\\[[\\d]{2}\\]){1}(.\\1){0,2}$')], verbose_name='Code'),
        ),
    ]
