# Generated by Django 3.0.6 on 2020-06-07 09:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0005_auto_20200607_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^([\\d]{2}){1}(.\\1){0,2}$')], verbose_name='Code'),
        ),
    ]
