# Generated by Django 3.0.6 on 2020-06-07 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0006_auto_20200607_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='research',
            name='added_by',
        ),
    ]
