# Generated by Django 3.0.6 on 2020-06-08 06:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('research', '0007_remove_research_added_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='code',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^([\\d]{2}){1}(.\\1){0,2}$')], verbose_name='Код'),
        ),
        migrations.AlterField(
            model_name='research',
            name='academic_advisor',
            field=models.CharField(max_length=50, verbose_name='Руководитель'),
        ),
        migrations.AlterField(
            model_name='research',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.Category', verbose_name='Рубрика ГРНТИ'),
        ),
        migrations.AlterField(
            model_name='research',
            name='critical_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.CriticalTechnology', verbose_name='Наименование критической технологии РФ'),
        ),
        migrations.AlterField(
            model_name='research',
            name='economic_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.EconomicPriority', verbose_name='Наименование приоритетного направления модернизации и технологического развития экономики России'),
        ),
        migrations.AlterField(
            model_name='research',
            name='reasons',
            field=models.TextField(verbose_name='Основнание для выполнения'),
        ),
        migrations.AlterField(
            model_name='research',
            name='scientific_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.ScientificPriority', verbose_name='Наименование приоритетного направления развития науки, технологий и техники РФ'),
        ),
        migrations.AlterField(
            model_name='research',
            name='strategic_direction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.StrategicDirection', verbose_name='Наименование направления, определенного в Стратегии научно-технологического развития Российской Федерации'),
        ),
        migrations.AlterField(
            model_name='research',
            name='university_priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.UniversityPriority', verbose_name='Наименование приоритетного направления в рамках Программы развития ДВФУ и Программы повышения конкурентоспособности Дальневосточного федерального университета среди ведущих мировых научно-образовательных центров на 2013–2020 гг.'),
        ),
    ]
