# Generated by Django 3.0.6 on 2020-06-08 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_auto_20200608_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='project_manager',
            field=models.CharField(max_length=100, verbose_name='Project Manager'),
        ),
    ]
