# Generated by Django 3.0.6 on 2020-06-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_auto_20200608_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='contest',
            field=models.CharField(max_length=300, verbose_name='Название конкурса'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='fond',
            field=models.CharField(max_length=50, verbose_name='Название фонда'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='program',
            field=models.CharField(blank=True, max_length=200, verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='project',
            field=models.CharField(max_length=300, verbose_name='Название проекта'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='project_manager',
            field=models.CharField(max_length=100, verbose_name='Руководитель проекта'),
        ),
    ]
