# Generated by Django 3.0.6 on 2020-06-21 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0005_auto_20200615_0923'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['fond'], 'verbose_name': 'Проект, поданный сотрудником ДВФУ на конкурс в отчетном году', 'verbose_name_plural': 'Проекты, поданные сотрудниками ДВФУ на конкурсы в отчетном году'},
        ),
        migrations.RenameField(
            model_name='contest',
            old_name='project_manager',
            new_name='manager',
        ),
        migrations.AlterField(
            model_name='contest',
            name='date_added',
            field=models.DateField(auto_now_add=True, verbose_name='Дата добавления'),
        ),
        migrations.AlterField(
            model_name='contest',
            name='fond',
            field=models.CharField(max_length=50, verbose_name='Название фонда/организации'),
        ),
    ]
