# Generated by Django 3.0.6 on 2020-06-22 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0006_auto_20200621_0302'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ['fond'], 'verbose_name': 'Конкурсный проект', 'verbose_name_plural': 'Конкурсные проекты'},
        ),
        migrations.AlterField(
            model_name='contest',
            name='project',
            field=models.CharField(max_length=300, unique=True, verbose_name='Название проекта'),
        ),
    ]
